package project.model.xmler.templater;

import org.jdom2.Document;
import org.jdom2.Element;

public class CityDocumentTemplater implements IDocumentTemplater {
    @Override
    public Document getTemplate() {
        Document document = new Document();

        Element root = new Element("citiesCatalog");

        Element informationElement = new Element("information");
        informationElement.addContent(new Element("authored").setText("Auto generated by CitySearcher v1.0"));

        Element citiesElement = new Element("cities");

        root.addContent(informationElement);
        root.addContent(citiesElement);
        
        document.setContent(root);
        
        return document;
    }
}
